name: Feature design / RFC
description: Submit a detailed feature request with a concrete proposal, including an exhaustive API design
labels: [ feature, 'status: needs triage' ]
body:
  - type: markdown
    attributes:
      value: |
        Important things:

        - This is for feature request including a real API design, not just a basic idea.
        - The design does not have to be perfect, we'll discuss it if needed.
        - For a more "casual" feature request, consider using GitHub Discussions instead: https://github.com/wulianapp/chainless-api-ts/discussions/categories/ideas


  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines?
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/wulianapp/chainless-api-ts/blob/master/CONTRIBUTING.md).
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: input
    attributes:
      label: Has this been requested on GitHub Discussions?
      description: Please post the [GitHub Discussions](https://github.com/wulianapp/chainless-api-ts/discussions/categories/ideas) link, it is helpful to see how much interest there is for this feature.

  - type: textarea
    attributes:
      label: Motivation
      description: Please outline the motivation for the proposal and why it should be implemented.
    validations:
      required: true

  - type: textarea
    attributes:
      label: API design
      description: |
        Please describe how users will use this feature.
        
        Please explain in an exhaustive way what are the config options and their respective effects.
        
        > **What happens if you skip this step?** This issue may be closed without any in-depth discussion. Your feature request is just an idea for now, please use GitHub Discussions for that: https://github.com/wulianapp/chainless-api-ts/discussions/categories/ideas


  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below.
        If you do check this box, please send a pull request within 7 days so we can still delegate this to someone else.
        
        Note that for feature issues, we still require you to fully fill out this form and reach consensus with the maintainers on API design before rushing to implement it, so that you don't waste your time.
      options:
        - label: I'd be willing to contribute and develop this feature myself.
